### ISSUE TITLE
大神，无论是之前版本还是今天的新版，竞赛不能点击。

### ISSUE THREAD

**Issue by 85524365** [Tq7/AutoJs-QiangGuoDaTi#6]
大神，安卓8.0，华为p9plus，AutoX.js 6.2版本， 默认时间511，
能四人赛或者双人赛界面，第一题就不能点击，一直等到别人获胜，不知道是什么原因。
恳请指点一下，会是设置或者插件的问题吗？膜拜了

**Comment by Tq7** [comment]
我用的是AutoX.js v5.7.8，这种情况应该不是版本的原因。可能是你遇到了太强的对手，第一题作答之前如果落后对手，会默认进行无效局。

**Comment by 85524365** [comment]
感谢大神百忙中答复

**Comment by lnliwei** [comment]
华为手机一直就不好用。到答题界面就不动了，和答题速度无关。

**Comment by Tq7** [comment]
> 华为手机一直就不好用。到答题界面就不动了，和答题速度无关。

请自行查找问题出在哪一行，答题界面截个图

**Comment by CuteLicense** [comment]
5156 、5157行 x0 y0 坐标改为题目序号后面 黑点（.） 的坐标，应该是找不到这个点的原因

**Comment by Tq7** [comment]
@attte 加我QQ1345424384

**Comment by Tq7** [comment]
@lnliwei 今天更新的应该能用了

**Comment by CuteLicense** [comment]
@attte  不是能不能获取的问题，而是获取的坐标在不同手机上不一定都准确，至少在我的手机上就这样，用其他工具定一下坐标

**Comment by lnliwei** [comment]
@Tq7 大神真厉害，新版本华为手机能用了，不知道改哪里了。

**Comment by CuteLicense** [comment]
新版本的确解决了这个问题

**Comment by lnliwei** [comment]
![image](https://user-images.githubusercontent.com/84962445/159402114-d20d4aec-2574-4b87-ba56-2e5e0f6614ce.png)

**Comment by Tq7** [comment]
> 

已修复，感谢反馈！
